# Site settings
course_name: "CS564: Machine Learning"
course_description: "Course website for CS564 at IIT Patna. Contains lectures, assignments, and announcements."

course_semester: "Fall 2025"

# Update for your repo
baseurl: "" # since this is a GitHub Pages project site, leave empty unless hosted under subpath
url: "https://cs564-iitp.github.io" # the base hostname & protocol for your site

schoolname: "Indian Institute of Technology Patna"
schoolurl: "https://www.iitp.ac.in"

# twitter_username: username  # <- commented out, not needed

address: |
    Department of Computer Science and Engineering
    IIT Patna
    Bihta, Patna, India

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false   # changed to true so announcements appear on site

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
